### ISSUE TITLE
Component is not compatible with the 6.10.* version

### ISSUE THREAD

**Issue by Matroskeen** [mariodavid/cuba-component-taggable#3]
After upgrading to 6.10.0 version there is a warning message in the CUBA Studio console:

`WARN: The following application components are not compatible with the platform version of the project (6.10.0): de.diedavids.cuba.taggable (6.9.3).`

Anyway, it works. I'm not sure can we ignore it or not.

**Comment by mariodavid** [comment]
Hi,

You can ignore it. Its just a warning from studio.

It is not tested, but there is nothing special in this plugin, which will stop working in 6.10...

I will do the version bump qt some point. But you can just use it in 6.10

**Comment by utrost** [comment]
Hello Mario, 

As you suggested I give it a shot to modify this plugin for mysql. for Cuba 6.9.6 it compiles fine after changing the database. But when I try to upgrade the plugin to the most recent version I run into an issue:

I have tried to upgrade 

- the dependencies to
--  de.diedavids.cuba.entitysoftreference:entity-soft-reference-global:0.4.0
-- de.balvi.cuba.declarativecontrollers:declarativecontrollers-global:0.7.0
- and the cuba version to 6.10.6

when running the project i get the following error:

`:taggable-global:compileJavaC:\Users\Uwe\cuba\cuba-component-taggable\modules\global\src\de\diedavids\cuba\taggable\entity\Tagging.java:16: error: incompatible types: Entity cannot be converted to Annotation
@Entity(name = "ddct$Tagging")`

**Comment by utrost** [comment]
Disregard. Comiples now :-)

**Comment by mariodavid** [comment]
0.3.0 released which contains CUBA 6.10 support.
